
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_41920_development


test:
  <<: *default
  database: furima_41920_test

production:
  <<: *default
  database: furima_41920_production
  username: furima_41920
  password: <%= ENV["FURIMA_41920_DATABASE_PASSWORD"] %>
